### ISSUE TITLE
Alternate method to set the face size of the hex head bolt

### ISSUE THREAD

**Issue by MrEsc927** [aminGhafoory/parametric-knob-maker#1]
I really like your elegant design, for some of my personnel projects in OpenSCAD I use the Apothem calculation and use cylinder instead of cube.     I also noted for the face size of 8 (so an M8 bolt) the default THRU_HOLE_DIAM was a bit small so initially when looking at the output from below the hole looked very small to the hex head size.    Setting the thru hole to 9 diameter and face size to 8 looks t match the bolt head closer.

module FaceToFaceHex(width,height){

FaceApothem=((sqrt(3)/2)*SCREWHEAD_FACETOFACE);
hex=6;
	cylinder(r=FaceApothem,h=height,$fn=hex,center=true);
/*
    cube([width/sqrt(3),width,height],center = true,$fn=64);
    rotate([0,0,120])cube([width/sqrt(3),width,height],center = true);
    rotate([0,0,240])cube([width/sqrt(3),width,height],center = true);
*/	

}

**Comment by MrEsc927** [comment]
not sure what happened the multiplication symbol did not paste in the note    The correct variable assignment below.

FaceApothem=((sqrt(3)/2)*SCREWHEAD_FACETOFACE);

**Comment by aminGhafoory** [comment]
thank you for your response but for m8 screw you should enter 12.73 to13 for `SCREWHEAD_FACETOFACE` look at DIN standard for screws `SCREWHEAD_FACETOFACE `is `S` in the table
[DIN srandard](https://user-images.githubusercontent.com/74732606/185756495-7f6f163c-b045-4414-8dcd-da2969b41138.jpg)

**Comment by aminGhafoory** [comment]
your method is really neat and simple but i chose this method because if you have a screw on hand and you don't know what kind is it you can simply measure  the distance  between two faces of hex screw head with just a ruler but measuring the radius of it without a caliper is hard 
 if you want to use your method  instead  `s` in DIN standard sheet use `e` on DIN standard sheet
